# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"f\n\x0cProtobufData\x12\t\n\x01\x41\x18\x01 \x01(\t\x12\t\n\x01\x42\x18\x02 \x01(\t\x12\t\n\x01\x43\x18\x04 \x01(\t\x12\t\n\x01\x44\x18\x05 \x01(\t\x12\t\n\x01\x45\x18\x06 \x01(\t\x12\t\n\x01\x46\x18\x08 \x01(\t\x12\t\n\x01G\x18\x0e \x01(\t\x12\t\n\x01H\x18\x10 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROTOBUFDATA']._serialized_start=14
  _globals['_PROTOBUFDATA']._serialized_end=116
# @@protoc_insertion_point(module_scope)
